version: "3.9"

networks:
  lite_demo-net:
  
volumes:
  common_volume:
    external: true

services:
  test_api:
    image: datascientest/fastapi:1.0.0
    container_name: test_api
    networks:
      - lite_demo-net
    ports:
      - target: 8000
        published: 8000

  test_authentification:
    depends_on:
        test_api:
          condition: service_started
    image: test_authentification:latest
    container_name: test_authentification
    networks:
      - lite_demo-net
    volumes:
      - common_volume:/app/logs
    environment:
      LOG: 1
    tty: true